# Generated by Django 3.0.11 on 2021-02-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0174_merge_20201222_1031'),
        ('pretix_attestation_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationLink',
            fields=[
                ('string_url', models.CharField(max_length=4096)),
                ('order_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pretixbase.OrderPosition')),
            ],
        ),
    ]
